version: "2"

networks:
  DGRAPH_DEV:
    driver: bridge

services:
  zero:
    image: dgraph/dgraph:v23.0.0
    container_name: "zero-dgraph"
    volumes:
      - ./dgraph_data/zero:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: "no"
    networks:
      - DGRAPH_DEV
    command: dgraph zero --my=zero:5080

  alpha:
    image: dgraph/dgraph:v23.0.0
    container_name: "alpha-dgraph"
    volumes:
      - ./dgraph_data/alpha:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
      - 8000:8000
    restart: "no"
    networks:
      - DGRAPH_DEV
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=0.0.0.0/0 --graphql "debug=true;introspection=true;extensions=true;lambda-url=http://dgraph_lambda:8686/graphql-worker;"

  dgraph_lambda:
    image: dgraph/dgraph-lambda:v1.4.1
    container_name: dgraph_lambda
    ports:
      - "8686:8686"
    environment:
      DGRAPH_URL: http://alpha:8080
    volumes:
      - ./dist/bundle.js:/app/script/script.js:ro
    networks:
      - DGRAPH_DEV

  ratel:
    container_name: dgraph-ratel
    image: "dgraph/ratel:latest"
    ports:
      - "9000:8000"
