on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
name: CI
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Packages
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build Lambda Bundle
        run: npm run build:production
      - name: Run Containers
        run: docker-compose up -d
      - name: Validate Schema
        run: bash validate_schema.sh
