on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
name: CI
jobs:
  CI:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Packages
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build:production
